### ISSUE TITLE
U-Net 3+

### ISSUE THREAD

**Issue by AKMourato** [open-mmlab/mmsegmentation#1005]
Greetings,

I believe U-Net 3+ would be a significant add-on to your provided architectures.

Are you planning to incorporate it here?

Info:
[(https://arxiv.org/abs/2004.08790)](url)
repo:
https://github.com/ZJUGiveLab/UNet-Version

Thanks

**Comment by MengzhangLI** [comment]
Hi, I already marked this paper several months ago. In my opinion, I would like to incporate it (because of its relative high citation and github star number in its field) into MMSegmentation right after refactoring UNet and adding UNet ++. The latter two are more influencial and widely known in medical image segmentation task.

But we do not have clear time schedule about this model because we are very busy these days. Would you like to make a PR to support UNet 3+ (just follow the structure of [UNet](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/backbones/unet.py))? 

Best,
