### ISSUE TITLE
ValueError: size shape must match input shape. Input is 2D, size is 3

### ISSUE THREAD

**Issue by zougougou** [open-mmlab/mmsegmentation#1048]
Hello, I have this problem while running my own dataset

 `ValueError:` size shape must match input shape. Input is 2D, size is 3_
My configuration document is modified based on this
`deeplabv3_r50-d8_512x512_20k_voc12aug.py`
in `voc.py`:
`    
    CLASSES = ('background', 'darea')
    PALETTE = [[0, 0, 0], [255, 255, 255]]`
My image and mask are three channels,I refer to the same problem, but it still hasn't been solved

**Comment by MengzhangLI** [comment]
Hi, I think it is caused by your mask has 3 channels. Could it be transferred into 1 channel?

**Comment by zougougou** [comment]
Thank you for your reply!
I try to change the mask to  1 channel.
Do I need to modify my tag value[255,255,255]?
But now there is another mistake:
`terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered`
The specific error information is as follows:
![image](https://user-images.githubusercontent.com/48472248/142151148-658263ae-7c27-4afe-832d-53d138b34bb5.png)
![image](https://user-images.githubusercontent.com/48472248/142151185-a583590f-3507-49e5-9ba3-cdb25aff3e61.png)

**Comment by MengzhangLI** [comment]
Hi, I think tag value is ok because it has sth to do with visual effects of prediction file.

Could you check out image and gt file in [pseudo cityscapes dataset](https://github.com/open-mmlab/mmsegmentation/tree/master/tests/data/pseudo_cityscapes_dataset), I think if you follow its shape and format. You would not meet troubles.

But feel free to talk to me if troubles still encounter.

Best,

**Comment by zougougou** [comment]
With your help, I found my problem.Mask pixel value should be label value.Thank you very much!

**Comment by WangYe7** [comment]
> 在你的帮助下，我发现了我的问题。遮罩像素值应为标签值。谢谢！


我想知道你是怎么操作的

> 在你的帮助下，我发现了我的问题。遮罩像素值应为标签值。谢谢！
