### ISSUE TITLE
use the auxiliary head with different ground-truth to ground-truth of the main task

### ISSUE THREAD

**Issue by vince2003** [open-mmlab/mmsegmentation#1058]
Hello,
I need to use a model having 2 tasks: the main task with the main segmentation ground-truth, the auxiliary task with an auxiliary segmentation ground-truth. 

How can I config the model with 2 types of segmentation ground-truth?

Thank you!

**Comment by MengzhangLI** [comment]
Hi, in MMSegmentation codebase. The ground truth of decoder head and auxiliary head/heads are the same ground truth. The only difference is in test mode, the auxiliary head/heads would not take up computation resources. They are only involved in auxiliary training in training mode.

So your design cannot be realized easily on MMSegmentation.

**Comment by vince2003** [comment]
Thank you for your reply. Can you suggest the idea for my design?

**Comment by MengzhangLI** [comment]
> Thank you for your reply. Can you suggest the idea for my design?

Honestly, currently it is not supported because your idea needs many code refactoring in MMSegmentation. Especially split of annotation/ images of datasets, loss calculation and many other existing code pipeline.

But if I understand well, you want to do some joint training work, like different tasks share most part of network with small part of it is unique. We would consider add this tasks in the future.

**Comment by vince2003** [comment]
Thank you very much!!!
