### ISSUE TITLE
TypeError: evaluate( got an unexpected keyword argument 'pre_eval'?

### ISSUE THREAD

**Issue by tensorflowt** [open-mmlab/mmsegmentation#1074]
Hi! I have recently been training the segmentation network FCN using the MMSEG framework！
When I finished training for the 4000th time, I encountered the following error when I needed to verify the model's accuracy！
![mmseg](https://user-images.githubusercontent.com/37217594/143393671-cb0368d2-e6bb-4a46-896f-e1814512471d.png)
My Conda environment is as follows：
![22](https://user-images.githubusercontent.com/37217594/143393737-741b69e2-d309-4446-bb35-8303e1d74d9f.png)
How do I solve this problem? thank you！

**Comment by MengzhangLI** [comment]
Hi, I think it is caused by mmcv version. `pre_eval` may be changed in MMCV. So could you try to upgrade your mmcv and mmsegmentation (if it would not damage your modification on MMSegmentation repo) ? 

Actually `1.3.8` is a little bit old. So you can upgrade mmcv and try again. Looking forward to your feedback. 

Best,
