### ISSUE TITLE
About cityscapes' performance

### ISSUE THREAD

**Issue by Vipermdl** [open-mmlab/mmsegmentation#1094]
Hi, I'm a fresher in mmseg, I have a naive problem yet I can't fix it. Sorry to bother you. When I used [ocrnet script](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/ocrnet/ocrnet_hr18s_512x1024_40k_cityscapes.py) to train HRNetV2p-W18-Small backbone in cityscapes, the performance in val is below:
![image](https://user-images.githubusercontent.com/32351961/144152617-50ddb877-811c-4d2f-94d4-a49f63bc0938.png)
I check the log in offical, and found something is different with mine: As the script, we choose the max_iters=40000, but I found when my max_iters=4000, the epoch = 27, but the release in official epoch is 108. 
![image](https://user-images.githubusercontent.com/32351961/144153000-b0916af4-75fd-4b53-afdb-9d5f0d54eb3d.png)
Is this problem? and how to fix it? 
Thanks!

**Comment by MengzhangLI** [comment]
I guess it may be caused by different GPU cards? Did you use your single GPU card?

For example, from [log](https://download.openmmlab.com/mmsegmentation/v0.5/ocrnet/ocrnet_hr18s_512x1024_40k_cityscapes/ocrnet_hr18s_512x1024_40k_cityscapes_20200601_033304.log.json) is 4 GPU: `GPU 0,1,2,3: Tesla V100-SXM2-32GB` with [2 samplers per GPU](https://github.com/open-mmlab/mmsegmentation/blob/62346e2791ae3f85bba0153b6e34fe85841e0c38/configs/_base_/datasets/cityscapes.py#L35). Thus totall batch sizes are 4x2 = 8.

**Comment by Vipermdl** [comment]
Thanks! I got it!
