### ISSUE TITLE
关于classes和palette

### ISSUE THREAD

**Issue by Lsz-20** [open-mmlab/mmsegmentation#1151]
由于使用了自行拟定的数据集，所以按照说明修改了config/dataset和mmseg/dataset里面的对应内容，其中也修改了CLASSES[]和PALETTE[]两个list的内容，当我train结束运行tools/test.py时发现最终输出的图像每个类对应的颜色并非上面文件中设置的，请问是哪里有问题呢？
譬如class：ABC对应palette：RGB，但是最后test所得到的是BRG
感谢回复

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply. It is caused by mmcv.imread, which is inherited from cv2, so its loading image is BGR format. I think you could change palette order, for example, current certain palette of class is [255, 0, 0], you may change it to [0, 0, 255] and try again.

BTW, next time please use english for better discussion around the world.

Best,

**Comment by Lsz-20** [comment]
> Hi, sorry for late reply. It is caused by mmcv.imread, which is inherited from cv2, so its loading image is BGR format. I think you could change palette order, for example, current certain palette of class is [255, 0, 0], you may change it to [0, 0, 255] and try again.

ok，thanks for your advice
