### ISSUE TITLE
Logical batch size.

### ISSUE THREAD

**Issue by StuLiu** [open-mmlab/mmsegmentation#1177]
There is one GPU only in my computer. Therefore, I can't reproduce the metrix produced by 4 GPU as shown in your readme.md.
Could you please implement the function of 'logical batch size'. So I can train with only one GPU at the cost of training time, and reproduce the similar metrix.

**Comment by MengzhangLI** [comment]
Hi, you can train with one gpu instead of four gpu by change corresponding `samples_per_gpu` to four times as before, and set only one gpu to train. The related batch size could be change here:

https://github.com/open-mmlab/mmsegmentation/blob/ff9d695b4051e9f2384da11ba4dbdef5d003a856/configs/bisenetv1/bisenetv1_r18-d32_4x4_1024x1024_160k_cityscapes.py#L9

**Comment by StuLiu** [comment]
> 

Thanks for your instruction. However, the OOM Error was caused by limited memory (24GB is still not enough).

**Comment by StuLiu** [comment]
> Hi, you can train with one gpu instead of four gpu by changing corresponding `samples_per_gpu` to four times as before, and set only one gpu to train. The related batch size could be change here:
> 
> https://github.com/open-mmlab/mmsegmentation/blob/ff9d695b4051e9f2384da11ba4dbdef5d003a856/configs/bisenetv1/bisenetv1_r18-d32_4x4_1024x1024_160k_cityscapes.py#L9

Thanks for your instruction. However, the OOM Error was caused by limited memory (24GB is still not enough).

**Comment by MengzhangLI** [comment]
Try to use FP16, have a look on this config:

https://github.com/open-mmlab/mmsegmentation/blob/master/configs/bisenetv2/bisenetv2_fcn_fp16_4x4_1024x1024_160k_cityscapes.py
