### ISSUE TITLE
Boundary loss

### ISSUE THREAD

**Issue by IgorDavidyuk** [open-mmlab/mmsegmentation#1198]
Hello! Thank you so much for the framework.
Do you plan to introduce any boundary-based loss function?

**Comment by MengzhangLI** [comment]
Hi, not yet.

Do you mean boundary loss published in MIDL? https://arxiv.org/pdf/1812.07032.pdf

We do not have a clear plan for this loss function because our development plan is already overloaded.

And whats more, (1) boundary loss is difficult to add (it needs calculate nearest distance of each pixel to the surface), (2) in many natural image dataset such as Cityscapes and ADE20K, it has many classes (i.e., 19 and 150, respectively), which make their signed distance function / distance map very complicated, so personally I really doubt the performance of boundary loss on natural image dataset.

If you really want to implement, you can find this repo: https://github.com/JunMa11/SegWithDistMap. It works well in LiTS tumour dataset, but it is really not stable. I know because I ran these experiments.

Best,

**Comment by IgorDavidyuk** [comment]
Thank you! I will look into that repo.
