### ISSUE TITLE
Doubt Regarding labels - ADE20K

### ISSUE THREAD

**Issue by kanlions** [open-mmlab/mmsegmentation#1509]
I have a doubt regarding the labels of ADE20K. I need to run experiments on this dataset. But since I am new to this library I am currently  running experiments on the pre trained models from the zoo. One thing I noticed that inference segmentor returns a 2D array where the labels are IDX -1- For example I notice 2 for sky, 4 for tree etc. Can the developers explain the labeling in mmsegmentation. As I need to calculate the metrics like IOU etc. I am not sure how the labels and where the GT labels are saved in mmsegmentation.
Please clarify

**Comment by MengzhangLI** [comment]
First, I am more appreciated if you could be more polite when asking for help rather than makig others "clarify".

Back to your question. 

Q1: One thing I noticed that inference segmentor returns a 2D array where the labels are IDX -1- For example I notice 2 for sky, 4 for tree etc. 

A1: **It is becasue label starts from `0` rather than `1`.** You can figure it out simply if you could train and check out log like here:

![image](https://user-images.githubusercontent.com/24582831/165065819-ab602fe0-15dc-417e-95b5-2a6d8eb17fb8.png)


Q2: Can the developers explain the labeling in mmsegmentation. As I need to calculate the metrics like IOU etc. I am not sure how the labels and where the GT labels are saved in mmsegmentation.

A2: I suggest refer to [inference.md](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/inference.md), using `--eval mIoU` can get mIoU metric like here:

![image](https://user-images.githubusercontent.com/24582831/165066640-cb493527-129b-4afd-badd-858a97d2898d.png)

The logit value of each image prediction is here: https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/segmentors/encoder_decoder.py#L256. Then it would be discarded by `argmax` function.

The metric evaluation function is called here: https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/apis/test.py#L219.

The GT are called here: https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/custom.py#L299. And its upstream code is below:

![image](https://user-images.githubusercontent.com/24582831/165071307-115548b1-c2cc-4f9e-a548-3b909a87e94c.png)

**Comment by kanlions** [comment]
Thanks a lot for all the help as I was struggling to find the internal code and apologies if you find rude. Unfortunately I am not a native English speaker and generally use please clarify.

**Comment by MengzhangLI** [comment]
> Thanks a lot for all the help as I was struggling to find the internal code and apologies if you find rude. Unfortunately I am not a native English speaker and generally use please clarify.

It's OK Kanjar, feel free to ask questions if you meet any problems when debugging.

**Comment by MengzhangLI** [comment]
Hi, @kanlions Kanjar, sorry I think I forgot to tell you important information: If you check the annotation file, the index range of official requirement is from 0 to 150. But the index range of output is from 0 to 149 because set `reduce_zero_label=True`.

Please check out this file: https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/ade.py#L14-L20.

Feel free to contact us if you meet problems in the future.
