### ISSUE TITLE
LearningRateDecayOptimizerConstructor

### ISSUE THREAD

**Issue by ydhongHIT** [open-mmlab/mmsegmentation#1623]
The current LearningRateDecayOptimizerConstructor seems to have no support for 'custom_keys'.

**Comment by MengzhangLI** [comment]
Yes, because it is added just for re-implementing  BEiT and ConvNeXt, no preparation for other usage. I suggest you may follow its original method for your customization.

https://github.com/facebookresearch/ConvNeXt/blob/main/semantic_segmentation/mmcv_custom/layer_decay_optimizer_constructor.py

https://github.com/microsoft/unilm/blob/master/beit/semantic_segmentation/mmcv_custom/layer_decay_optimizer_constructor.py
