### ISSUE TITLE
Multi-channel image input for segmentation (probably tiff)

### ISSUE THREAD

**Issue by FranzEricSchneider** [open-mmlab/mmsegmentation#1668]
Hi, we're interested in training on some multi-spectral data where there are more than 3 image channels. I see from https://github.com/open-mmlab/mmsegmentation/issues/810 and https://github.com/open-mmlab/mmsegmentation/issues/1033 that this was know to be not possible back in 2021, has this changed in 2022?

In particular I was looking at this section of the FCN Unet config, which looks like the input channels could be set to something other than 3. It would be great to be able to run Unet on these tiff images, for example.
```
backbone=dict(
    type='UNet',
    in_channels=3,
    ...
)
```

If the limitation on 1 or 3-channel images still exists, we might be interested in taking a shot at it and submitting a PR to mmseg. If possible, could you talk a bit about what would need to be done and what the roadblocks would likely be? That would really help jump-start work on it. ([@russelldj](https://github.com/russelldj/) also interested).

- Is there a portion of the code that deals with data import that would need to be the initial focus?
- Data augmentation seems like it would be one roadblock, where does that code live? What seems like the hardest part of that?
- Are there any other big roadblocks that stick out to you?
- Are there any tests (automated or hand-run) that you would want to run to confirm this worked?

**Comment by MengzhangLI** [comment]
Hi, @FranzEricSchneider @russelldj

I try to summarize some feedbacks to you, if it is not very clear feel free to talk to me.

- The most important things about multi-channel tiff images on MMSegmentation is how to use it in data transform **pipeline**, because MMSegmentation uses pipeline in config to handle data transform, like [here](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/datasets/isaid.py#L15-L26):
```python
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
crop_size = (896, 896)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=(896, 896), ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]
```

- Data Transform code is located at [here](https://github.com/open-mmlab/mmsegmentation/tree/master/mmseg/datasets/pipelines), it is initiated at [`__init__.py`](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/__init__.py) and defined at each python file like [here](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/transforms.py#L860-L976)

- The most important thing is ensure **pipeline** could handle situation channels > 3, where some default settings need to be changed like `norm` because `img_norm_cfg = dict(mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)` above is obviously used for 3-channel RGB image, so do certain other data transform.

- Could you please list some useful information of adding multi-channel TIFF remote sensing segmentation to us? I could debug and try to build an original pipeline of MMSegmentation. For example: (1) Name of dataset you want (2) Which data augmentations are necessary to add, (3) which evaluation metrics, benchmarks and SOTA models are necessary. 

After building the primary pipeline (I would think about it from now on), the PRs from community are always welcomed and they are always top priorities for us. Let us work together to add more features of multi-channel remote sensing segmentation tasks to serve global community. 

Best,

**Comment by MengzhangLI** [comment]
Hi, sorry to bother you again!

Do you have some plans about this proposal? @FranzEricSchneider @russelldj

**Comment by MengzhangLI** [comment]
Due to no reply I would close this issue. Anyone wants to contribute this feature could reopen it anytime.

**Comment by FranzEricSchneider** [comment]
Hello @MengzhangLI thank you for the information, sorry for the late reply, I was checking in about this with David. After some discussion it looks like this is of some interest to us but is not the first priority for the projects we're working on. It's possible we'll be able to work on it later but isn't the first thing to work on. Sorry about that.

**Comment by bbgame605065444** [comment]
I am also working with multiband remote sensing data, if you want. I can share some dataset with you. I hope that every kind of augmentation can be used on this datatype.

**Comment by MengzhangLI** [comment]
> 

Sure, it's very kind. By the way, could you list some data augmentation methods MMSegmentation not provided yet but necessary for your dataset?

**Comment by MengzhangLI** [comment]
> 

Sure, it's very kind. By the way, could you list some data augmentation methods MMSegmentation not provided yet but necessary for your dataset?
