### ISSUE TITLE
How to test my own dataset with mmsegmentation

### ISSUE THREAD

**Issue by Jinshan99** [open-mmlab/mmsegmentation#1865]
Hello, I want to test with the trained model in my notebook. I followed the Colab of the mmsegmentation, But I just after the train_segmentor(model, datasets, cfg, distributed=False, validate=True, 
                meta=dict()), I don't know how to test it, Could anyone help me?? THANK YOU!!!!!

**Comment by MengzhangLI** [comment]
For single image, you could use command [here](https://github.com/open-mmlab/mmsegmentation/blob/master/demo/inference_demo.ipynb).

For your customized dataset, because our demo just only supports guidance for beginners so it mainly supports single image rather than whole dataset. If you want to test on own dataset I suggest you abandon colab and following docs [customize_datasets.md](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/zh_cn/tutorials/customize_datasets.md), [get_started.md](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/zh_cn/get_started.md) and [inference.md](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/zh_cn/inference.md).

Also, you should convert your own dataset into MMSegmentation style, please refer to this [unofficial doc](https://github.com/MengzhangLI/mmsegmentation/blob/add_doc_customization_dataset/docs/zh_cn/tutorials/customize_datasets.md#%E5%A6%82%E4%BD%95%E5%87%86%E5%A4%87%E8%87%AA%E5%B7%B1%E7%9A%84%E6%95%B0%E6%8D%AE%E9%9B%86).

Feel free to contact us if you meet other problems.

Best,

**Comment by Jinshan99** [comment]
Hi, I have a folder contains test images for segmentation, I have train the model through train_segmentor(model, datasets, cfg, distributed=False, validate=True, 
                meta=dict()) and save the best checkpoint is saved as best_mIoU_iter_200.pth.    How could I use this to test my own datasets(png format) I want to get some result similar to the training process.. Thank you!!

**Comment by MengzhangLI** [comment]
Sorry for late reply. Just use `best_mIoU_iter_200.pth` as checkpoint and run `python tools/test.py ${CONFIG} ${CHECKPOINT} --eval mIoU`.
