### ISSUE TITLE
How to implementation the mIoU for objects edges only.

### ISSUE THREAD

**Issue by AkideLiu** [open-mmlab/mmsegmentation#2046]
I would like to implement an additional evaluation hook to evaluate the performance differences for object boundaries. Could you please give me some idea of what a good starting point for implementation is? 

The is an example of edge; suppose that edge detection progress could be made during run time instead modified the GT.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/41593290/189055374-1009dbde-e2f8-4fbe-b416-a57ab5321152.png">

**Comment by MengzhangLI** [comment]
I suggest using laplacian kernel & theshold to filter the edge because calculating edge based on distances of each types of foreground are very time-consuming.

You could follow how [STDC](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/decode_heads/stdc_head.py#L10-L85) works and read the original paper.

![image](https://user-images.githubusercontent.com/24582831/190436073-fc100377-b972-464c-88ff-ac5d36afba04.png)

**Comment by JordanMakesMaps** [comment]
These papers on calculating [boundary IoU](https://arxiv.org/abs/2103.16562) and [boundary loss](https://www.aaai.org/AAAI22Papers/AAAI-2277.WangC.pdf) might be of use. @MengzhangLI any chance these could be included in the repo?

**Comment by MengzhangLI** [comment]
We do not have enough time to add boundary loss, if you are interested in it, PR is absolutely welcome!

**Comment by xiexinch** [comment]
backlog 
https://github.com/open-mmlab/mmsegmentation/issues/2750
