### ISSUE TITLE
accuracy 损失函数

### ISSUE THREAD

**Issue by lkyyef** [open-mmlab/mmsegmentation#2058]
训练segmenter时想使用损失函数如下
 loss_decode=[
            dict(type='accuracy', loss_weight=1)
        ]
但是报错
KeyError: 'EncoderDecoder: "SegmenterMaskTransformerHead: \'accuracy is not in the models registry\'"'

**Comment by MengzhangLI** [comment]
Because `accuracy` is not loss in MMSegmentation, for example the `DiceLoss` has this [line](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/losses/dice_loss.py#L50).

If you want to customize new loss function, please follow this [doc](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/customize_models.md#add-new-loss).

**Comment by lkyyef** [comment]
Thank you for your answer
