### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Manningchan** [open-mmlab/mmsegmentation#2108]
The training is ok, but cuda out of memory will appear during the validation process. No matter it is a single gpu or multiple gpus, this error will occur. When i reduce the batch size, it is still appear,  i use 4 gpus, 8 samples per gpu in training is ok, but 2 samples per gpu in validation will occur the error
RuntimeError: CUDA out of memory. Tried to allocate 8.67 GiB (GPU 0; 23.70 GiB total capacity; 9.21 GiB already allocated; 4.45 GiB free; 17.61 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by MengzhangLI** [comment]
https://github.com/open-mmlab/mmsegmentation/blob/master/docs/en/tutorials/customize_datasets.md#data-configuration

In validation, there is always one image one time:

```
samples_per_gpu only works for model training, and the default setting of samples_per_gpu is 1 in mmseg when model testing and validation (DO NOT support batch inference yet).
```

I think perhaps it is (1) caused by your validation set has a large quantities of images than training set, or (2) your original images sizes are too big (in training, before training model it will crop images into `crop_size` size).

**Comment by Manningchan** [comment]
> 

thank you， i find that some validation images are too big and the codes can run after resized these images
