### ISSUE TITLE
Some questions about adding edge supervision module

### ISSUE THREAD

**Issue by endaoguansanlu** [open-mmlab/mmsegmentation#2246]
Hi, what should I do if I want to add an edge supervision module to the backbone network and then use BCELoss as the loss function? I looked at the code of the decoding header and found that the number of output channels must be the number of categories of the dataset, and the number of output channels of the edge module is generally 1, so do I only need to change the 'use_sigmoid' in 'CELoss config' change to 'True' to achieve this. Looking forward to your reply!!!!!!!!

**Comment by MengzhangLI** [comment]
Hi, why you want to add edge supervision module on backbone network rather in decoder head or auxiliary head, because I think you should add this module in heads.

If you want to use edge supervision, I can give you two suggestions. First, you can read [STDC](https://github.com/open-mmlab/mmsegmentation/tree/master/configs/stdc), which has a Detail Aggregation module by integrating the learning of spatial information into low-level layers in single-stream manner to learn edge.
Second, you can check [Generate Edge](https://github.com/open-mmlab/mmsegmentation/pull/2210) to get edge ground truth and treat all these edge pixels as new labels.

**Comment by endaoguansanlu** [comment]
Thank you so much for your generous advice! ! ! I'll go and do some research T_T
