### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by scm-later** [open-mmlab/mmsegmentation#2317]
On the same dataset, using the same settings, why do I spend the same time training with two video cards as with one video card

**Comment by MengzhangLI** [comment]
Hi, because the total batch size of your model is not the same, for example in ADE20K dataset, you can set samplers per GPU [here](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/datasets/ade20k.py#L35).

If you want to accelerate training process, you could make `samples_per_gpu` half of original setting when using two GPUs.

**Comment by MeowZheng** [comment]
This issue is inactive for a long time, and I'll close it. If anyone has any questions, please reopen it at any time.
