### ISSUE TITLE
Detailed feature prediction performance is poor

### ISSUE THREAD

**Issue by ASONG0506** [open-mmlab/mmsegmentation#2344]
![1543048816731600](https://user-images.githubusercontent.com/26050577/203691008-5460323b-7174-479a-9a74-d4ceba09f4d1.png)
![1543046612946109](https://user-images.githubusercontent.com/26050577/203691025-059fbe9f-a55a-4dd5-b704-b3bee5852ede.png)

Hi，I use deeplabv3 to do 4-class segmentation, here is my config file: 
[deeplabv3_r50-d8_512x512_4x4_40k_trunk3.py.txt](https://github.com/open-mmlab/mmsegmentation/files/10080726/deeplabv3_r50-d8_512x512_4x4_40k_trunk3.py.txt)

As you can see in these prediction pictures, the laneline result is very poor, any one know what's wrong, thank you!

**Comment by MengzhangLI** [comment]
Hi, from your results above, I think the model training is not wrong because the truck, road the laneline predictions are close to objects.

I think laneline result does not meet your requirement just because this type of foreground is discrete on the image, and its pixel numbers are also less than truck's and roads'. 

If you want to improve performance, you can try some more up-to-date models like swin transformer and SegFormer.

Also, you can try to increase the class weight of laneline. Here is [doc](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/zh_cn/tutorials/training_tricks.md#%E7%B1%BB%E5%88%AB%E5%B9%B3%E8%A1%A1%E6%8D%9F%E5%A4%B1-class-balanced-loss).

Best,

**Comment by ASONG0506** [comment]
@MengzhangLI thanks for your apply

actually  i tried to set the class weight but the result is also not very good, and this is the result in bisenetv2 paper on cityscapes datset, as you can see, the lamppost prediction is very good. I think the lamppost label is the same as laneline, so I still cannot understand why my result is so poor.
![image](https://user-images.githubusercontent.com/26050577/203694202-7ed091e3-82fc-4074-b6aa-b0f40aea0e7b.png)

**Comment by MengzhangLI** [comment]
I think the dataset is different, your own dataset is different with Cityscapes. You can train another model which just change dataset config to cityscapes to checkout model performance.
