### ISSUE TITLE
predicted class is not the same as my setting

### ISSUE THREAD

**Issue by ASONG0506** [open-mmlab/mmsegmentation#2345]
in my dataset config, there is two class named ['background', 'lane'], whose palette is [[120,120,120], [6, 230,230]], but when I do inference, there is 3 palette in the result including [[120,120,120], [6, 230,230],[0,0,0]], show as follow, what's the problem, thanks!
![image](https://user-images.githubusercontent.com/26050577/203694674-9a6ad727-dfc4-48a7-ae2f-2f1d2e1f9cc2.png)

the class and palette setting 
```
    CLASSES = ('background', 'roi')

    PALETTE = [[120, 120, 120], [6, 230, 230]]

```
the gt label for example,
![image](https://user-images.githubusercontent.com/26050577/203695086-ef414baa-a431-459f-88a0-cf3153a15c97.png)

**Comment by MengzhangLI** [comment]
Hi, @ASONG0506 I think it is a binary segmentation problem which it only has one foreground class.

You can refer to this [doc](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/zh_cn/faq.md#%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86%E4%BA%8C%E5%80%BC%E5%88%86%E5%89%B2%E4%BB%BB%E5%8A%A1). Because I think your problem is caused by wrong config setting.

Best,
