### ISSUE TITLE
How can I see input format of dataset (like H,W, max values, etc.)?

### ISSUE THREAD

**Issue by islomjn** [open-mmlab/mmsegmentation#2370]
How can I see input format of dataset (like H,W, max values, etc.) as well as output from training (like H,W, max values, etc.) before calculating metrics?

**Comment by MengzhangLI** [comment]
First, I think "H,W, max values, etc." you mentioned is not of "dataset" but "feature map". And calculating metric is only in validation/test process rather than training process  (but when you run `./tools/train.py`, it would have validation process).

I think the key line is [here](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/apis/test.py#L91).

**Comment by islomjn** [comment]
Hello! Thank you very much for your response. How is it possible to see predictions in validation phase from mmseg.apis 
 `train_segmentor` function, if ``validate=True`` during training?

**Comment by MengzhangLI** [comment]
> Hello! Thank you very much for your response. How is it possible to see predictions in validation phase from mmseg.apis `train_segmentor` function, if `validate=True` during training?

You have to visualize manually, i.e., use the tensor [here](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/segmentors/encoder_decoder.py#L279).

**Comment by islomjn** [comment]
Understood. Thank you!
