### ISSUE TITLE
model PIDNet request

### ISSUE THREAD

**Issue by Sere1nz** [open-mmlab/mmsegmentation#2401]
# Describe the feature
model PIDNet request

**Motivation**
A clear and concise description of the motivation of the feature.

There is a recent paper [PIDNet: A Real-time Semantic Segmentation Network Inspired from PID Controller](https://arxiv.org/abs/2206.02066), which is very helpful for real time semantic segmentation with high fps and IoU.

**Related resources**
https://github.com/XuJiacong/PIDNet

**Comment by MengzhangLI** [comment]
Hi, thanks for your recommendation. We would record this model in our backlog.

Unfortunately, we are not able to support this method in the near future because of limited human resources. If you really want to use it, we can work together, you make a PR for PIDNet and we would review it as soon as possible.

Best,
