### ISSUE TITLE
How is the default threshold of 0.3 determined?

### ISSUE THREAD

**Issue by jackkwok** [open-mmlab/mmsegmentation#2414]
Why is the default threshold not `0.5`? It defaults at `0.3`.

https://github.com/overjetdental/mmsegmentation/blob/master/mmseg/models/decode_heads/decode_head.py#L109

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.

The default value `0.3` was introduced in https://github.com/open-mmlab/mmsegmentation/pull/2016. We did not use `0.5` because we found `0.5` performed very bad, worse than `0.3` in many cases. You can try other values for free if you want because there is no conclusion that `0.3` is best. 

Best,
