### ISSUE TITLE
bin size in APCNet

### ISSUE THREAD

**Issue by catmiao108** [open-mmlab/mmsegmentation#2641]
APCNet paper： “ {1, 2, 3, 6, 32}: bin sizes of pooled feature, 1 × 1, 2 × 2, 3 × 3, 6 × 6, 32 × 32.”
what does “bin sizes”mean？

**Comment by Junjun2016** [comment]
Hi @catmiao108 
 “bin sizes” mean the shapes of pooled feature, e.g., the shape of the input feature is [b, c, h, w] and the input feature will be pooled to [b, c, 1, 1], [b, c, 2, 2], [b, c, 3, 3], [b, c, 6, 6], and [b, c, 32, 32] respectively for each branch, that's why we call it "pyramid feature".

**Comment by catmiao108** [comment]
> Hi @catmiao108 “bin sizes” mean the shapes of pooled feature, e.g., the shape of the input feature is [b, c, h, w] and the input feature will be pooled to [b, c, 1, 1], [b, c, 2, 2], [b, c, 3, 3], [b, c, 6, 6], and [b, c, 32, 32] respectively for each branch, that's why we call it "pyramid feature".

Ok, thanks for your reply.

**Comment by catmiao108** [comment]
> Hi @catmiao108 “bin sizes” mean the shapes of pooled feature, e.g., the shape of the input feature is [b, c, h, w] and the input feature will be pooled to [b, c, 1, 1], [b, c, 2, 2], [b, c, 3, 3], [b, c, 6, 6], and [b, c, 32, 32] respectively for each branch, that's why we call it "pyramid feature".

ok, thanks for your reply.
