### ISSUE TITLE
Ensure batch size of 2 in EpochBasedRunner with uneven number of training samples

### ISSUE THREAD

**Issue by PhilippMarquardt** [open-mmlab/mmsegmentation#3192]
Hi,

I want to use an EpochBasedTrainer which works fine if the number_of_training_images%batch_siz==0. But for example if I use a batch size of 2 and I have an uneven number of training images (669 in my case), is there any way to force always having 2 samples per batch even if there is only 1 more available? Because if I use an epoch based runner with a batch size of 2 and an uneven number of training samples the last batch will only have 1 image and always result in a ValueError("Expected more than 1 value per channel when training, got input size {}".format(size)) ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512, 1, 1]). 

Thanks!

**Comment by PhilippMarquardt** [comment]
I fixed it by setting `drop_last = True` in the train_dataloader

**Comment by xuhan199606** [comment]
I looked it up online because batchsize is not divisible by the number of datasets. So you need to set drop_last = False, but for mmseg, I don't know where to set this parameter. When I try to change batchsize to a divisible value, I get no error. Can you share where you set drop_last = True? Maybe change drop_last = True to drop_last = False.

**Comment by PhilippMarquardt** [comment]
You need to set drop_last=True so the last batch does not get processed (The problem is I guess if the last batch has only 1 item and batch norm is used, the layer causes an error because only 1 item is in there).
Simply set `train_dataloader = dict(
    batch_size=2,
    num_workers=0,
    persistent_workers=False,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type='BaseSegDataset',
        data_root=
       whatever/',
        img_suffix='.png',
        data_prefix=dict(img_path='train/images', seg_map_path='train/labels'),
        pipeline=[
            dict(type='LoadImageFromFile', imdecode_backend='cv2'),
            dict(type='LoadAnnotations', reduce_zero_label=False),
            dict(type='Resize', scale=(512, 512), keep_ratio=False),
            dict(type='RandomFlip', prob=0.5),
            dict(type='PackSegInputs')
        ],
        metainfo=dict(classes=('0', '1', '2', '3')),
        reduce_zero_label=False),
    drop_last=True)` for example in the config. So just set drop_last in the dataloader

**Comment by xuhan199606** [comment]
I still have problems following your idea, whether it is set to true or false. My current solution is to force batchsize to be divisible, but I know this is not the final solution.



—————————————
Name:  xuhan
Email: ***@***.***


---- Replied Message ----
| From | Philipp ***@***.***> |
| Date | 03/31/2024 19:56 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [open-mmlab/mmsegmentation] Ensure batch size of 2 in EpochBasedRunner with uneven number of training samples (Issue #3192) |

You need to set drop_last=True so the last batch does not get processed (The problem is I guess if the last batch has only 1 item and batch norm is used, the layer causes an error because only 1 item is in there).
Simply set train_dataloader = dict( batch_size=2, num_workers=0, persistent_workers=False, sampler=dict(type='DefaultSampler', shuffle=True), dataset=dict( type='BaseSegDataset', data_root= whatever/', img_suffix='.png', data_prefix=dict(img_path='train/images', seg_map_path='train/labels'), pipeline=[ dict(type='LoadImageFromFile', imdecode_backend='cv2'), dict(type='LoadAnnotations', reduce_zero_label=False), dict(type='Resize', scale=(512, 512), keep_ratio=False), dict(type='RandomFlip', prob=0.5), dict(type='PackSegInputs') ], metainfo=dict(classes=('0', '1', '2', '3')), reduce_zero_label=False), drop_last=True) for example in the config. So just set drop_last in the dataloader
