### ISSUE TITLE
Training on higher resolution

### ISSUE THREAD

**Issue by anish9** [open-mmlab/mmsegmentation#545]
Can we expect the performances to be the same when switching 512x512 to 1900x1900 resolutions, assuming the training original image size is above 2000x20... range.

**Comment by Junjun2016** [comment]
Hi @anish9 
It is hard to say, to some extent, the larger the original image, the larger the crop size.
But if the crop size is too large, the current data augmentation method is not very suitable, because the difference after data augmentation is smaller, maybe we need to adjust the data augmentation strategy.
You can conduct experiments with different crop sizes based on your dataset. Currently, there is no general rule and we look forward to someone who can give a solution in the future.
