### ISSUE TITLE
size shape must match input shape. Input is 2D, size is 3

### ISSUE THREAD

**Issue by soltkreig** [open-mmlab/mmsegmentation#550]
I got the mistake:
size shape must match input shape. Input is 2D, size is 3
I use images and masks (512,512,3)

**Comment by xvjiarui** [comment]
Hi @soltkreig 
What command and what config are you using?

**Comment by soltkreig** [comment]
Hi @xvjiarui. I've solved this trouble use this code (just re-read images and save again):
```
for file in mmcv.scandir(osp.join(root, masks), suffix='.png'):
    seg_map = cv2.imread(osp.join(root, masks, file), cv2.IMREAD_GRAYSCALE)
    seg_img = Image.fromarray(seg_map).convert('P')
    seg_img.putpalette(np.array(palette, dtype=np.uint8))
    seg_img.save(osp.join(root, masks, file))
```
and I really don't know why it helped

**Comment by cdrwolfe** [comment]
My guess is that it expects the mask image / annotation to be 1D value and not a 3D RGB value. 

From tutorial:

Note: The annotations are images of shape (H, W), the value pixel should fall in range [0, num_classes - 1]. You may use 'P' mode of pillow to create your annotation image with color.

It's probably not the clearest explanation.

**Comment by MengzhangLI** [comment]
Hi @soltkreig

Seems like it is caused by mmcv default settings.

Here is another similar issue https://github.com/open-mmlab/mmsegmentation/issues/626, please check it out.

**Comment by AxeBlue** [comment]
> 

But VOC dataset seems like (H,W,3)

**Comment by WangYe7** [comment]
> Hi @xvjiarui. I've solved this trouble use this code (just re-read images and save again):
> 
> ```
> for file in mmcv.scandir(osp.join(root, masks), suffix='.png'):
>     seg_map = cv2.imread(osp.join(root, masks, file), cv2.IMREAD_GRAYSCALE)
>     seg_img = Image.fromarray(seg_map).convert('P')
>     seg_img.putpalette(np.array(palette, dtype=np.uint8))
>     seg_img.save(osp.join(root, masks, file))
> ```
> 
> and I really don't know why it helped
where should this code be placed

**Comment by Jeff001128** [comment]
I have also encountered this error ' Input is 2D, size is 3 '. This is because mmsegmentation requires the mask to be of size [H, W], without the channel dimension. As my mask dimension was of size [512, 512, 3], the error was raised.

To tackle the problem, you can go to mmseg/datasets/pipelines/loading.py and find the __call__ function of the class LoadAnnotations, then change the sentence 'gt_semantic_seg = mmcv.imfrombytes(img_bytes, flag=’unchanged’,backend=self.imdecode_backend).squeeze().astype(np.uint8)' to 'gt_semantic_seg = mmcv.imfrombytes( img_bytes, flag='grayscale', backend=self.imdecode_backend).squeeze().astype(np.uint8)'. The flag controls the image reading method, and 'grayscale' can ignore the third dimension and read the mask correctly.

I also sincerely recommend mmsegmentation to improve the aforementioned sentence, as it would cause undesired mistakes if the mask has 3 channels. @MengzhangLI
