### ISSUE TITLE
How to use the ignore_index ?

### ISSUE THREAD

**Issue by nikhilbyte** [open-mmlab/mmsegmentation#554]
I have 24 labels to predict and I want to ignore the 24th class. So should I set the value of ignore_index as "23" or "[0,0,0]" ?

**Comment by nistarlwc** [comment]
the value of the 24th class is "255"

**Comment by MengzhangLI** [comment]
Hi, if you want to ignore 24th class, you could add `ignore_index` value into loss function in your config files.

For example, you could add this value in this place:

![WXWorkCapture_16245144481896](https://user-images.githubusercontent.com/24582831/123212724-ba261280-d4f7-11eb-93b1-befab4d0af71.png)

Adding `ignore_index = 23`, because the class number starts from 0. 

Best,

**Comment by Childhoo** [comment]
When I add this ignore_index to the config file, then the following errors happens during building segmentor

TypeError: EncoderDecoder: FCNHead: CrossEntropyLoss: __init__() got an unexpected keyword argument 'ignore_index'

@nikhilbyte Could you please let me know whether adding ignore_index works or not in your case? Thank you.
