### ISSUE TITLE
is there no need to initialize the weight of decoder?

### ISSUE THREAD

**Issue by h1063135843** [open-mmlab/mmsegmentation#586]
`
self.backbone.init_weights(pretrained=pretrained)
self.decode_head.init_weights()
`
why decode_head don't need to initialize with pretrained model.
`
    def init_weights(self):
        """Initialize weights of classification layer."""
        normal_init(self.conv_seg, mean=0, std=0.01)
`
And in the fact init_weights only init the classification layer in basic decoder, other decode-heads even don't have this function

**Comment by Junjun2016** [comment]
Hi @h1063135843 
Sorry for the late reply. Generally, a segmentor consists of backbone, neck, and decoder head, for backbone, we will use ImageNet pretrained weights to initialize since transferring knowledge from ImageNet is helpful for nature image segmentation with large models. While for the neck and decoder head, we will use the default initializer in PyTorch. 
If we want to initialize a module or a layer with a specific initializer, we can define an initializer in `init_cfg` (refer to [initialize](https://github.com/open-mmlab/mmcv/blob/master/mmcv/cnn/utils/weight_init.py#L465)).

**Comment by h1063135843** [comment]
> we can define an initializer in `init_cfg`

Thanks for your reply. The init_cfg is just what I need.
