### ISSUE TITLE
In the process of training, loading data will be abnormal periodically.

### ISSUE THREAD

**Issue by jianlong-yuan** [open-mmlab/mmsegmentation#611]
![image](https://user-images.githubusercontent.com/18137551/122761275-a481d480-d2ce-11eb-9e0b-4cf8a2693382.png)

As shown in the red box of the figure, reading data will be abnormal periodically. This will greatly affect the training efficiency. 

Hardware environment: Tesla V100 16G

Software environment:
mmsegmentation         0.12.0  
mmcv-full              1.2.6
torch                  1.6.0
torchvision            0.7.0

**Comment by jianlong-yuan** [comment]
any news?

**Comment by MengzhangLI** [comment]
Hi, jianlong.

It is weird because I re-check the pipleline and seems it is always normal in my environment. I use single GPU and train PSPNet in cityscapes dataset.

<img width="1440" alt="截屏2021-06-23 上午11 49 08" src="https://user-images.githubusercontent.com/24582831/123032817-3b5aa800-d419-11eb-8f52-ea860397522b.png">


How many GPUs your experiment use and does other task share CPUs and GPUs in your server?

Because data loading is always related with I/O of CPU, could you give us more detailed information? For example, the location of data (SSD/ HDD, home dir or other disk dir, it may affect I/O), whether other tasks share computation sources.

Best,

**Comment by jianlong-yuan** [comment]
Hi, I just use a server with 8GPUS. There is no other task on the server. The data is located at SSD,  /home.

**Comment by MengzhangLI** [comment]
OK, I see. It's a little bit weird because I never met this problem before.

From your description, it has nothing to do with other process or storage disk.

Could you try other models / GPU numbers(or single GPU) / datasets to see whether this phenomenon still exist?

Looking forward to your responses.

Best,

**Comment by jianlong-yuan** [comment]
I've tried. Different models have the same problem, and different numbers of GPUs have the same problem. However, this problem only occurs on the NVIDIA GPU V100 16G, and all NVIDIA GPUs V100 16G have the same problem, but on other machines, such as 32g NVIDIA GPU or P100, there is no such problem.

**Comment by MengzhangLI** [comment]
Ok, let me record this issue for next time our inner discussion.

Actually the snapshot I showed above is on my  NVIDIA GPU V100 16G server. I trained PSPNet on cityscapes in one 16G V100 GPU.

In the next few days, I will check whether it could happens on my identical environment: 8*V100 (16G) && Ubuntu OS.

If other GPU is OK for you, please use them currently. I will give my results a few days later. 

Best,

**Comment by jianlong-yuan** [comment]
In addition, I use centos.

**Comment by MengzhangLI** [comment]
Hi, @jianlong-yuan

Do you use (1) your customized dataset  and (2) it is a little bit small?

If your situation meets up (1) && (2), maybe it is caused by conflict of dataloader and multithreading in small data. Give a shot by enlarging its scale, just [repeat or concatenate](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/customize_datasets.md) your own dataset. 

Let us see whether it could be fixed.

Best,

**Comment by jianlong-yuan** [comment]
But dataset 

> Hi, @jianlong-yuan
> 
> Do you use (1) your customized dataset and (2) it is a little bit small?
> 
> If your situation meets up (1) && (2), maybe it is caused by conflict of dataloader and multithreading in small data. Give a shot by enlarging its scale, just [repeat or concatenate](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/customize_datasets.md) your own dataset.
> 
> Let us see whether it could be fixed.
> 
> Best,

Hi, thank you. Data sets are generally not too large, often hundreds to thousands of images. But I can't expand the data set. Expanding the data set causes unfair comparison. Is there any other solution?

**Comment by jianlong-yuan** [comment]
Any news?

**Comment by Junjun2016** [comment]
Hi @jianlong-yuan 
You can repeat the dataset or update your PyTorch version to 1.8 which sets the `persistent_worker=True` in our default setting.

**Comment by Junjun2016** [comment]
> Expanding the data set causes unfair comparison

Repeat dataset is the same as concatenating the same dataset many times.

**Comment by jianlong-yuan** [comment]
@Junjun2016 @MengzhangLI 
Following @Junjun2016 suggestion, I update your PyTorch version to 1.8 which sets the persistent_worker=True in our default setting. Then everything goes well. Is there any way could support the lower versions?

![image](https://user-images.githubusercontent.com/18137551/127116461-9ba42b3c-6e05-4855-b058-f1724f1d38ff.png)

**Comment by Junjun2016** [comment]
> @Junjun2016 @MengzhangLI
> Following @Junjun2016 suggestion, I update your PyTorch version to 1.8 which sets the persistent_worker=True in our default setting. Then everything goes well. Is there any way could support the lower versions?
> 
> ![image](https://user-images.githubusercontent.com/18137551/127116461-9ba42b3c-6e05-4855-b058-f1724f1d38ff.png)

It only supports PyTorch>=1.7.0.
Hi @dreamerlin 
Could you please share the way to set `persistent_worker` work with PyTorch>=1.7.0, <1.8.0?

**Comment by Junjun2016** [comment]
> > @Junjun2016 @MengzhangLI
> > Following @Junjun2016 suggestion, I update your PyTorch version to 1.8 which sets the persistent_worker=True in our default setting. Then everything goes well. Is there any way could support the lower versions?
> > ![image](https://user-images.githubusercontent.com/18137551/127116461-9ba42b3c-6e05-4855-b058-f1724f1d38ff.png)
> 
> It only supports PyTorch>=1.7.0.
> Hi @dreamerlin
> Could you please share the way to set `persistent_worker` work with PyTorch>=1.7.0, <1.8.0?

Please set `pin_memory` to `False` when PyTorch>=1.7.0, <1.8.0.
Looking forward to your feedback.

**Comment by jianlong-yuan** [comment]
Is it support Pytorch 1.6?

**Comment by Junjun2016** [comment]
> Is it support Pytorch 1.6?

No.
