### ISSUE TITLE
label load error

### ISSUE THREAD

**Issue by jinseok-karl** [open-mmlab/mmsegmentation#626]
Hi, thanks to sharing this great code!
When I customize pspnet, I met an error when evalutaion.
I use cityscape format. When validate, the function mmseg/core/evaluation/metric/intersec_and_union seem to applied.
But, I get label which shape [512,512,3]. I think the third channel is not necessary.
Is it wrong?

**Comment by MengzhangLI** [comment]
Hi, thanks for your nice word on MMSegmentation.

First, I rechecked the `label` in `mmseg/core/evaluation/metric/intersect_and_union`, the dataset is cityscapes whose input image size is [1024, 2048], the label is the same [1024, 2048]:
<img width="1440" alt="截屏2021-06-23 上午11 31 29" src="https://user-images.githubusercontent.com/24582831/123031259-9a6aed80-d416-11eb-988d-e012c58cfc4f.png">

Thus I guess this phenomenon may caused by customized dataset and its config. For example, your default or your new config file and its train/test pipeline has the shape [512, 512, 3] (p.s. Is your customize data size [512, 512]? ) and it affects the validation. You can check [customized dataset tutorial](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/customize_datasets.md) and [config tutorial](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/config.md) for detailed information. 

But just as my debug figure, the shape of `label` should not have channel number.

Could you recheck and show related `variables` in `train_pipeline`/`test_pipeline` and  `label` in `mmseg/core/evaluation/metric/intersect_and_union`?

**Comment by jinseok-karl** [comment]
Thanks to explain!
I experimented on customdata  just modifying data path of configs/_base_/datasets/cityscapes.py 
So It seems no different with your experient.
I think [512,512,3] is come from img_file raw size. Because psp_net(769x769) may not deal with 512.
But It is weird that predicted label shape was [512,512] which means psp_net(769x769) may deal with 512.
Anyway, I'm steel finding the cause of this problem!
When I know exactly, I'll reply on here for beginner level user like me!

**Comment by jinseok-karl** [comment]
From debugging, It may depend on mmcv imread.
Because, I tested on original_dataset_GTmask and resized_dataset_GTmask.
Even if they same except for size, the former was read as gray scale, the latter was read as 3channel.
I don't know which cause maskGT become gray or 3channel,
by correcting mmseg/datasets/pipelines/loading.py and mmseg/datasets/custom.py where load annotations,
I can solve it!

**Comment by MengzhangLI** [comment]
Glad to hear you could solve this bug. ;)

This issue is meaningful for many user & contributor of MMSegmentation.

Best,

**Comment by Jeff001128** [comment]
> Hi, thanks for your nice word on MMSegmentation.
> 
> First, I rechecked the `label` in `mmseg/core/evaluation/metric/intersect_and_union`, the dataset is cityscapes whose input image size is [1024, 2048], the label is the same [1024, 2048]: <img alt="截屏2021-06-23 上午11 31 29" width="1440" src="https://user-images.githubusercontent.com/24582831/123031259-9a6aed80-d416-11eb-988d-e012c58cfc4f.png">
> 
> Thus I guess this phenomenon may caused by customized dataset and its config. For example, your default or your new config file and its train/test pipeline has the shape [512, 512, 3] (p.s. Is your customize data size [512, 512]? ) and it affects the validation. You can check [customized dataset tutorial](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/customize_datasets.md) and [config tutorial](https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/config.md) for detailed information.
> 
> But just as my debug figure, the shape of `label` should not have channel number.
> 
> Could you recheck and show related `variables` in `train_pipeline`/`test_pipeline` and `label` in `mmseg/core/evaluation/metric/intersect_and_union`?

Hi, thanks for your kind reply. However, when I read the ADEChallenge20k datasets, I found that the mask has 3 channels, which means the annotation shape is [xxx, xxx, 3]. All the experiments went on well on ADE20k datasets, while when I explored my own datasets, the error "size shape must match input shape. Input is 2D, size is 3" occurred. My own datasets' masks have the shape of [512, 512, 3], and I totally followed the dataloader of type ade.py. Could you help me with the issue? Thank you for your time.
