### ISSUE TITLE
Is there any method to fix backbone without training?

### ISSUE THREAD

**Issue by jianlong-yuan** [open-mmlab/mmsegmentation#648]

**Comment by MengzhangLI** [comment]
Hi, could you put across your question more detailed?

Do you mean certain well-trained backbone whose parameters are not only structure-fixed but also reaching state-of-the-art performance in various dataset?

Best,

**Comment by jianlong-yuan** [comment]
> Hi, could you put across your question more detailedly?
> 
> Do you mean certain well-trained backbone whose parameters are not only structure-fixed but also reaching state-of-the-art performance in various dataset?
> 
> Best,

Yes,  For some tasks, we need to fix backbone parameters without training.

**Comment by jianlong-yuan** [comment]
any news?

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply.

Of course you could modify the backbone structure although structure conflict may happen because modification may make parameters more or less and can not match the original pretrained backbone. So you may encounter `warning` or `error.`

If you only change some parameters which may not add or decrease model parameters such as `dilations`, it should work.

In summary, you could fix backbone as long as it could run, but the numerical results are unknown.
