### ISSUE TITLE
Can't find independent models

### ISSUE THREAD

**Issue by GTimothee** [open-mmlab/mmsegmentation#662]
Hi, 

I am just wondering how to get the models independently from the whole mmlab framework in order to train them by myself.

I already have such "runner" to train my models and it would save me a lot of time not to learn the whole mmlab framework just to use one of your model implementations (like in pytorch hub). 

Thanks

**Comment by MengzhangLI** [comment]
Hi, sorry for late reply. @GTimothee 

First, I suggest use the whole framework because of ongoing forum discussion, bug fix and new features. If you have questions, you could refer our detailed [english doc](https://github.com/open-mmlab/mmsegmentation/tree/master/docs) and [chinese doc](https://github.com/open-mmlab/mmsegmentation/tree/master/docs_zh-CN). It may be time-consuming but in the long term it deserves.

Return to the question itself, you could refer to `encoder_decoder.py`, the `extract_feat` is backbone and `_decode_head_forward_train` is segmentor head. 

https://github.com/open-mmlab/mmsegmentation/blob/f5be6e2617aae15915060598b3f8004f4d9aeea1/mmseg/models/segmentors/encoder_decoder.py#L138

https://github.com/open-mmlab/mmsegmentation/blob/f5be6e2617aae15915060598b3f8004f4d9aeea1/mmseg/models/segmentors/encoder_decoder.py#L142

Their input and output should be the same for most segmentation framework. Hoping it is helpful to you!

Best,
