### ISSUE TITLE
How to resize image(with keep ratio) and padding  image  by fixed size?

### ISSUE THREAD

**Issue by BboyHanat** [open-mmlab/mmsegmentation#675]
I resized image(with keep ratio) ,  then padding the image with fixed size, it's worked, but it's make image leaned on left and top side,   How to configure the train pipeline can keep image in center  after padding ?

**Comment by Junjun2016** [comment]
Hi @BboyHanat 
Sorry for the late reply.
You may modify the code in [MMSegmentation](https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/datasets/pipelines/transforms.py#L327) by passing `padding` instead of `shape` or modify the code in [MMCV](https://github.com/open-mmlab/mmcv/blob/master/mmcv/image/geometric.py#L482).

**Comment by Junjun2016** [comment]
https://github.com/open-mmlab/mmcv/blob/6659c38dd5f5485b35b776d6ed10505f94e161ae/mmcv/image/geometric.py#L482
modify
```python
        padding = (0, 0, shape[1] - img.shape[1], shape[0] - img.shape[0])
```
to
```python
        pad_h = shape[0] - img.shape[0]
        pad_w = shape[1] - img.shape[1]
        padding = (pad_w//2, pad_h//2, pad_w-pad_w//2, pad_h-pad_h//2)
```

**Comment by Junjun2016** [comment]
https://github.com/open-mmlab/mmcv/blob/6659c38dd5f5485b35b776d6ed10505f94e161ae/mmcv/image/geometric.py#L482
modify
```python
        padding = (0, 0, shape[1] - img.shape[1], shape[0] - img.shape[0])
```
to
```python
        pad_h = shape[0] - img.shape[0]
        pad_w = shape[1] - img.shape[1]
        padding = (pad_w//2, pad_h//2, pad_w-pad_w//2, pad_h-pad_h//2)
```
