### ISSUE TITLE
Dataset download links fails

### ISSUE THREAD

**Issue by jiequancui** [open-mmlab/mmsegmentation#819]
Hi

For Pascal Context, Pascal VOC datasets download links, they seem don't work now.

Can you provide me an updated link? Very Thanks.

**Comment by MengzhangLI** [comment]
Hi, @jiequancui 

I checked links from here: https://github.com/open-mmlab/mmsegmentation/blob/master/docs/dataset_prepare.md#prepare-datasets

They can all be downloaded. Maybe it is caused by network condition.

![image](https://user-images.githubusercontent.com/24582831/130724598-0d5d00c4-2a6e-49c0-b5a6-713d2dd3ba1f.png)

Best,

**Comment by jiequancui** [comment]
Thanks for your kind reply.

I will check my network condition.
