### ISSUE TITLE
Finetuning

### ISSUE THREAD

**Issue by Benybrahim** [open-mmlab/mmsegmentation#838]
Hello,

I just want to know if there is a way to finetune a model to a new dataset, in a way that we can freeze the network and train only the `decode_head`?

The parameter `load_from` seems only to work with finetuning for model with same number of classes.

Thank you in advance.

**Comment by MengzhangLI** [comment]
Hi, @Benybrahim 
It could not `freeze the network and train only the decode_head`. I think you can try to use certain trained model as checkpoint, just loading its `state_dict` weights (in this way you need to on your own) and continue training. Because it only uses the weight of trained model, thus number of classes could be different for another dataset.

**Comment by Benybrahim** [comment]
Okay @MengzhangLI , Thank you for your quick reply.
