### ISSUE TITLE
[Basic] I do not get why some __base__ configs does not have any dataset, runner, schedule, model linkage?

### ISSUE THREAD

**Issue by timothylimyl** [open-mmlab/mmsegmentation#898]
For most examples given, the configs will have links to the configuration files of the dataset, runner, schedule, and  model.

 [Link1](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/deeplabv3/deeplabv3_r50-d8_512x1024_40k_cityscapes.py) and [Link2](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/deeplabv3/deeplabv3_r50-d8_769x769_40k_cityscapes.py) will have the __base__ configuration link to all the necessary configurations. 

**However, there are configs file that just calls itself? I do not know what is happening ([Link3](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/deeplabv3/deeplabv3_r50b-d8_512x1024_80k_cityscapes.py).**

Also, compare link1 and 2 configs to link3,  there is no model configuration. There is only `__base__/models/deeplabv3plus_r50-d8.py` but not `deeplabv3plus_r50b-d8`. I am not too sure what's the difference. It seems that the pre-trained ResNet model is back to the PyTorch version for the `50b` one, but where is the model configuration file and how does it know to set up for schedule, runner and dataset?

**Comment by MengzhangLI** [comment]
Hi, your problem is caused by your wrong location of  `_base_` file.

Use your example config for explanation. The config file [Link3](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/deeplabv3/deeplabv3_r50b-d8_512x1024_80k_cityscapes.py) calls its `_base_` file [deeplabv3_r50-d8_512x1024_80k_cityscapes.py](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/deeplabv3/deeplabv3_r50-d8_512x1024_80k_cityscapes.py). [Link3](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/deeplabv3/deeplabv3_r50b-d8_512x1024_80k_cityscapes.py) does not call itself.

In the `_base_` file [deeplabv3_r50-d8_512x1024_80k_cityscapes.py](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/deeplabv3/deeplabv3_r50-d8_512x1024_80k_cityscapes.py) there is `'../_base_/models/deeplabv3_r50-d8.py'` which would calls [../_base_/models/deeplabv3_r50-d8.py](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/_base_/models/deeplabv3_r50-d8.py).

Also, you could change schedule, runner and dataset just as `_base_` file [deeplabv3_r50-d8_512x1024_80k_cityscapes.py](https://github.com/open-mmlab/mmsegmentation/blob/master/configs/deeplabv3/deeplabv3_r50-d8_512x1024_80k_cityscapes.py) contained.

Best,

**Comment by timothylimyl** [comment]
Hi @MengzhangLI,  got it! I missed the fact it is calling another `__base__` file, did not catch that it was a different name. I see what u did by just changing the backbone and calling everything else the same way by leveraging the base configurations that u have already made.
