### ISSUE TITLE
how to make sure about param 'batch_size' in an example config

### ISSUE THREAD

**Issue by MacavityT** [open-mmlab/mmsegmentation#908]
I want to run a baseline model based on the reference configuration, but they only gave param 'samples_per_gpu' without the num of gups. How can I make sure of it? Thanks for your attention!

**Comment by Junjun2016** [comment]
Refer to the corresponding log of the model. You can find the number of GPU it used. 发自 网易邮箱大师 ---- 回复的原邮件 ---- 发件人 ***@***.***> 日期 2021年09月25日 16:41 收件人 ***@***.***> 抄送至 ***@***.***> 主题 [open-mmlab/mmsegmentation] how to make sure about of param 'batch_size' in a example config (#908) I want to run a baseline model based on the reference configuration, but they only gave param 'samples_per_gpu' without the num of gups. How can I make sure of it? Thanks for your attention! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MacavityT** [comment]
@Junjun2016 
Thanks for your help. 👍
