### ISSUE TITLE
error in multi loss configuration

### ISSUE THREAD

**Issue by cnnAndBn** [open-mmlab/mmsegmentation#988]
the trick multi loss  introduced in https://github.com/open-mmlab/mmsegmentation/blob/master/docs/tutorials/training_tricks.md
_base_ = './fcn_unet_s5-d16_64x64_40k_drive.py'
model = dict(
    decode_head=dict(loss_decode=[dict(type='CrossEntropyLoss', loss_name='loss_ce', loss_weight=1.0),
            dict(type='DiceLoss', loss_name='loss_dice', loss_weight=3.0)]),
    auxiliary_head=dict(loss_decode=[dict(type='CrossEntropyLoss', loss_name='loss_ce',loss_weight=1.0),
            dict(type='DiceLoss', loss_name='loss_dice', loss_weight=3.0)]),
    )
reported error like:
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'weight'  @MengzhangLI

**Comment by PaulTHong** [comment]
Hey, I have met the same problem before. The reason is the version of my MMSegmentation codebase is not the same as the newest. So I replaced the code in mmseg/models/losses, mmseg/models/decode_heads，etc with the newest code.  Then it's solved. Unexpected keyword argument 'weight' may be caused by decode_heads/decode_head.py in old version didn't process when the type of loss is list (corresponding to multiloss with parameter loss_weight). 

You can check it. Though maybe we are not in the same trouble.
